### ISSUE TITLE
Application cause errors on Linux.

### ISSUE THREAD

**Issue by Hutsaliuk** [bleonard252/just_audio_mpv#1]
Trying to adopt my audio application for Linux. While migrating I faced up with next problems.
So that nothing interferes, I've created a new small and simple app and have the same issues.
I'm using Zorin OS (Ubuntu-based Linux). MPV was installed.

Problems:
1. Application gets next runtime exceptions right after runing:
```

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a value of the returned future's type: Closure: () => int
#0      _registerErrorHandler (dart:async/future_impl.dart:904:3)
#1      Future.catchError (dart:async/future_impl.dart:344:17)
#2      new JustAudioMPVPlayer.<anonymous closure>
package:just_audio_mpv/src/mpv_player.dart:96
#3      new JustAudioMPVPlayer.<anonymous closure>
package:just_audio_mpv/src/mpv_player.dart:95
#4      EventEmitter.emit
package:eventify/src/event_emitter.dart:108
#5      MPVPlayer.start.<anonymous closure>
package:mpv_dart/src/mpv.dart:1004
<asynchronous suspension>
Restarted application in 574ms.
flutter: [just_audio_mpv] MPV started
flutter: [just_audio_mpv] Starting to load...
flutter: {type: progressive, id: e2da3b4e-562b-445a-8ed7-e1333f351c33, uri: /home/valentyn/Downloads/Music/cassette_-_my_way.mp3, headers: null}
flutter: [just_audio_mpv] Loaded.
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a value of the returned future's type: Closure: () => int
#0      _registerErrorHandler (dart:async/future_impl.dart:904:3)
#1      Future.catchError (dart:async/future_impl.dart:344:17)
#2      new JustAudioMPVPlayer.<anonymous closure>
package:just_audio_mpv/src/mpv_player.dart:96
#3      new JustAudioMPVPlayer.<anonymous closure>
package:just_audio_mpv/src/mpv_player.dart:95
#4      EventEmitter.emit
package:eventify/src/event_emitter.dart:108
#5      MPVPlayer.start.<anonymous closure>
package:mpv_dart/src/mpv.dart:1004
<asynchronous suspension>
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a value of the returned future's type: Closure: () => int
#0      _registerErrorHandler (dart:async/future_impl.dart:904:3)
#1      Future.catchError (dart:async/future_impl.dart:344:17)
#2      new JustAudioMPVPlayer.<anonymous closure>
package:just_audio_mpv/src/mpv_player.dart:96
#3      new JustAudioMPVPlayer.<anonymous closure>
package:just_audio_mpv/src/mpv_player.dart:95
#4      EventEmitter.emit
package:eventify/src/event_emitter.dart:108
#5      MPVPlayer.start.<anonymous closure>
package:mpv_dart/src/mpv.dart:1004
<asynchronous suspension>

```

2. Application start playing automatically, after adding the audio source.

3. Can't start playing after a pause. AudioPlayer changes its status (can check it with player.playing getter) but music doesn't play.

4. Music continues playing after closing the application.

Simple main.dart:
```Dart
import 'package:flutter/material.dart';
import 'package:just_audio/just_audio.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late AudioPlayer player;

  void _startStopMusic() {
    setState(() {
      if (player.playing) {
        player.pause();
      } else {
        player.play();
      }
    });
  }

  @override
  void initState() {
    super.initState();
    player = AudioPlayer();
    player.setAudioSource(AudioSource.uri(
        Uri.parse('/home/valentyn/Downloads/Music/cassette_-_my_way.mp3')));
  }

  @override
  void dispose() {
    player.stop();
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Text('Is music paying: ${player.playing}'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _startStopMusic,
        tooltip: 'Start/Stop',
        child: Icon(player.playing ? Icons.pause : Icons.play_arrow),
      ),
    );
  }
}

```

**Comment by bleonard252** [comment]
1. What's the output of `flutter doctor` (out of curiosity)? I think I do know how to solve this, though.
2. I thought this was something that JustAudio did, and I set the states to reflect it. I'll double-check this.
3. Strange, this doesn't happen to come with any error messages, does it?
4. This doesn't appear within my power to stop, because MPV is a separate process that does not get killed with the Flutter process. I worked around this in my own application by using a `window_manager` feature that lets me call `player.stop()` on close, although this doesn't work if it's quit from the debugger.

**Comment by Hutsaliuk** [comment]
@bleonard252
Hello!
When do you plan your bugfix to be merged and will be available?

**Comment by noobar** [comment]
I confirmed that the latest commit fixes the problem. Thank you!

By the way, the format of `pubspec.yml` should be like this :relaxed: 

```
dependencies:
  just_audio_mpv:
    git:
      url: https://github.com/bleonard252/just_audio_mpv
      ref: afb2aa129ae62756042c58a227b519c856281437
```

**Environment**
* Ubuntu 20.04.4 LTS
* mpv 0.32.0


**Error log before updating**

```
flutter: [just_audio_mpv] MPV started
flutter: [just_audio_mpv] Starting to load...
flutter: {type: progressive, id: 2e8edd0e-b99c-4990-a0fa-4e7793c340fa, uri: file:///home/me/AndroidStudioProjects/myproject/test.wav, headers: null}
flutter: [just_audio_mpv] Loaded.
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a value of the returned future's type: Closure: () => int
#0      _registerErrorHandler (dart:async/future_impl.dart:904:3)
#1      Future.catchError (dart:async/future_impl.dart:344:17)
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:96:49)
#3      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:95:42)
#4      EventEmitter.emit (package:eventify/src/event_emitter.dart:108:22)
#5      MPVPlayer.start.<anonymous closure> (package:mpv_dart/src/mpv.dart:1004:9)
```

**Comment by bleonard252** [comment]
@Hutsaliuk can you confirm the fix works for you as well?

**Comment by Hutsaliuk** [comment]
@bleonard252 
Hi! 
Sorry, I can't check it because our app has been reworked to work with another extension.

**Comment by altrepo2022** [comment]
> @Hutsaliuk can you confirm the fix works for you as well?

it didn't work for me

**Comment by bleonard252** [comment]
> it didn't work for me

@altrepo2022 can you share your dependencies from pubspec.yaml, as well as the log?

**Comment by tytydraco** [comment]
Can we get this pushed out? I can confirm this works.

**Comment by bleonard252** [comment]
If this issue appears again, please file a new issue with output logs and `flutter doctor` information.
