### ISSUE TITLE
Unhandled Exception: error accessing property

### ISSUE THREAD

**Issue by bytecntrl** [bleonard252/just_audio_mpv#7]
**Which API doesn't behave as documented, and how does it misbehave?**
I'm encountering an error while calling setAudioSource audio player method.
I'm only using a local audio files.
I'm on arch linux, I've tried this on macOS and this works.

**Minimal reproduction project**
```
play() async {
    AudioPlayer audioPlayer = AudioPlayer();

    final ConcatenatingAudioSource _playlist = ConcatenatingAudioSource(
      useLazyPreparation: true,
      shuffleOrder: DefaultShuffleOrder(),
      children: [],
    );

    if (soundTracks.isEmpty) {
      return;
    }

    for (final elem in soundTracks) {
      _playlist.add(AudioSource.uri(Uri.parse("file://${elem.path}")));
    }

    await audioPlayer.setAudioSource(_playlist,
        initialIndex: 0, initialPosition: Duration.zero);
    await audioPlayer.setLoopMode(LoopMode.all);
    await audioPlayer.setShuffleModeEnabled(true);
   await audioPlayer.play();
  }
```
**Error messages**
```
flutter: MPV 1c72f77b-d3f7-4afa-9848-0dbb1977930a started
flutter: MPV 1c72f77b-d3f7-4afa-9848-0dbb1977930a loading track...
flutter: {type: concatenating, id: 95f87c48-f18b-4258-b8c8-db8e34500764, children: [{type: progressive, id: 6d964a96-af52-43ea-b240-8ddb2ded6219, uri: file:///home/francesco/Documenti/file_example_MP3_700KB.mp3, headers: null}, {type: progressive, id: 1938b472-356a-4fd0-a4e7-e67bcf236359, uri: file:///home/francesco/Documenti/edit_21.mp3, headers: null}, {type: progressive, id: cb636374-f214-4982-8f44-764623b5f6fc, uri: file:///home/francesco/Documenti/edit_10.mp3, headers: null}, {type: progressive, id: 7bbb83bc-42f8-4d95-8854-d87467934ea6, uri: file:///home/francesco/Documenti/edit_7.mp3, headers: null}, {type: progressive, id: d578cca5-28b6-40e2-b4fa-69ef7e3f2a51, uri: file:///home/francesco/Documenti/edit_3.mp3, headers: null}], useLazyPreparation: true, shuffleOrder: [0, 1, 2, 3, 4]}
flutter: MPV 1c72f77b-d3f7-4afa-9848-0dbb1977930a quitting at request
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      JustAudioMPVPlayer.update (package:just_audio_mpv/src/mpv_player.dart:30:24)
<asynchronous suspension>
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:61:7)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      JustAudioMPVPlayer.update (package:just_audio_mpv/src/mpv_player.dart:30:24)
<asynchronous suspension>
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:61:7)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      JustAudioMPVPlayer.update (package:just_audio_mpv/src/mpv_player.dart:30:24)
<asynchronous suspension>
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:61:7)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      JustAudioMPVPlayer.update (package:just_audio_mpv/src/mpv_player.dart:30:24)
<asynchronous suspension>
#2      new JustAudioMPVPlayer.<anonymous closure> (package:just_audio_mpv/src/mpv_player.dart:61:7)
<asynchronous suspension>

flutter: MPV 1c72f77b-d3f7-4afa-9848-0dbb1977930a exited
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: error accessing property
```
**Expected behavior**
The audio player should play.

**Desktop (please complete the following information):**

- OS: Arch linux

**Flutter SDK version**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on Arch Linux 6.3.9-arch1-1, locale it_IT.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Comment by bleonard252** [comment]
The logs indicate something is disposing `just_audio_mpv` early ("**quitting at request**", which confusingly is also the message used when `just_audio` automatically unloads it).

Can you give me a little more information on how `play()` is called? Is it being called by a widget that is getting disposed (by changing pages, for example)?

**Comment by bytecntrl** [comment]
The method is called from a list (the play() method above is called in the _playStopTrack method). 
This is the widget code:
```
import 'package:flutter/material.dart';
import 'package:soundmaster/local_database/hive/hiveobjs/sound_category/sound_category.dart';
import 'package:soundmaster/local_database/hive/hiveobjs/sound_track/sound_track.dart';
import 'package:soundmaster/sound_track_explorer/sound_track_explorer_element.dart';

class SoundTrackExplorerList extends StatefulWidget {
  const SoundTrackExplorerList(
      {super.key, required this.data, required this.changedElementSelection});

  final List<SoundTrackExplorerElement> data;
  final void Function() changedElementSelection;

  @override
  State<SoundTrackExplorerList> createState() => SoundTrackExplorerListState();
}

class SoundTrackExplorerListState extends State<SoundTrackExplorerList> {
  bool selectionMode = false;
  SoundTrack? playingTrack;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: widget.data.length,
        itemBuilder: (context, index) {
          List<SoundTrackExplorerElement>? data = widget.data;
          return Card(
            color: data[index].isSelected == true ? Colors.blue : null,
            child: InkWell(
                onTap: () => {_elementTap(data, index)},
                onLongPress: () => {_elementLongPress(data, index)},
                child: Row(children: [
                  Padding(
                    padding: const EdgeInsets.all(20.0),
                    child: Text(widget.data[index].soundTrack.title),
                  ),
                  _getSoundTrackChip(widget.data[index].soundTrack)
                ])),
          );
        },
      ),
    );
  }

  Chip _getSoundTrackChip(SoundTrack soundTrack) {
    String text;
    IconData icon;

    switch (soundTrack.soundCategory) {
      case SoundCategory.music:
        text = "Music";
        icon = Icons.music_note;
        break;
      case SoundCategory.background:
        text = "Background";
        icon = Icons.thunderstorm;
        break;
      case SoundCategory.fx:
        text = "Effect";
        icon = Icons.rocket;
        break;
      default:
        text = "Unknown";
        icon = Icons.question_mark;
        break;
    }

    return Chip(
      label: Text(text),
      avatar: Icon(
        icon,
        color: Colors.white,
      ),
      backgroundColor: Colors.pinkAccent,
      padding: EdgeInsets.symmetric(vertical: 5, horizontal: 10),
    );
  }

  void _elementTap(List<SoundTrackExplorerElement> data, int index) {
    if (!selectionMode) {
      _playStopTrack(data[index].soundTrack);
      return;
    }
    _switchElementSelection(data, index);

    if (!_elementsAreSelected(data)) {
      _deselectAllElements(data);
    }
  }

  //Sound Player
  void _playStopTrack(SoundTrack soundTrack) {
    if (playingTrack != null) {
      playingTrack!.stop();
      if (playingTrack!.key != soundTrack.key) {
        soundTrack.play(); // <-- here
        playingTrack = soundTrack;
      } else {
        playingTrack = null;
      }
    } else {
      soundTrack.play();
      playingTrack = soundTrack;
    }
  }

  //Selection
  void _elementLongPress(List<SoundTrackExplorerElement> data, int index) {
    _deselectAllElements(data);
    _enableSelectionMode(true);
    _switchElementSelection(data, index);
  }

  void _switchElementSelection(
      List<SoundTrackExplorerElement> data, int index) {
    setState(() => data[index].isSelected = !data[index].isSelected);
  }

  void _deselectAllElements(List<SoundTrackExplorerElement> data) {
    setState((() {
      for (var element in data) {
        element.isSelected = false;
      }
      _enableSelectionMode(false);
    }));
  }

  bool _elementsAreSelected(List<SoundTrackExplorerElement> data) {
    for (var element in data) {
      if (element.isSelected) {
        return true;
      }
    }
    return false;
  }

  void _enableSelectionMode(bool value) {
    selectionMode = value;
    widget.changedElementSelection();
  }
}
```

**Comment by bleonard252** [comment]
It looks like two things are happening.
1. You're creating a new player every time you change tracks.
2. Only one player is being created, and maybe not persisting.

This is starting to look like, at least in part, it's a bug in the library. I'll take a closer look and see if I can figure out what's going on from my end.

**Comment by bleonard252** [comment]
There appears to be a limitation with an underlying library which means that only one instance of MPV can be used at a time. For `just_audio_mpv`, this means that only one instance can be active on a system at any given time.

I've [filed an issue](https://github.com/KRTirtho/mpv_dart/issues/2) at that library for this.

**Comment by bleonard252** [comment]
The library's maintainer is not planning to fix this as they consider it superceded by the [media_kit](https://github.com/media-kit/media-kit) library (which runs in place of or perhaps alongside `just_audio`). I'm also aware of [just_audio_media_kit](https://pub.dev/packages/just_audio_media_kit) which is your best bet if this library doesn't work.
